Controllers/NombreController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication3.Data;

namespace WebApplication3.Controllers
{
    // Contrôleur
    public class NombreController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NombreController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var nombres = _context.Nombres.ToList();
            return View(nombres);
        }

        [HttpPost]
        public IActionResult Incrementer(int id)
        {
            var nombre = _context.Nombres.Find(id);
            if (nombre != null)
            {
                nombre.Nombre++;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult decrementer(int id)
        {
            var nombre = _context.Nombres.Find(id);
            if (nombre != null)
            {
                nombre.Nombre--;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Nombre/Index.cshtml
@model IEnumerable<NombreModel>

<table>
    @foreach (var nombre in Model)
    {
        <tr style="color: white;">
            <td>@nombre.Nombre</td>
            <td>
                <form asp-controller="Nombre" asp-action="Incrementer" method="post">
                    <input type="hidden" name="id" value="@nombre.Id" />
                    <button class="buttonM" type="submit">Incrémenter</button>
                </form>
            </td>
            <td>
                <form asp-controller="Nombre" asp-action="decrementer" method="post">
                    <input type="hidden" name="id" value="@nombre.Id" />
                    <button class="buttonM" type="submit">Decrémenter</button>
                </form>
            </td>
        </tr>
    }
</table>