Models/Voiture.cs
using System.ComponentModel.DataAnnotations;
using WebApplication3.Data.enums;

namespace WebApplication3.Models
{
    public class Voiture
    {
        [Key]
        public int Id { get; set; }
        public string image { get; set; }
        public string nom { get; set; }
        public double prix { get; set; }
        public int nombre { get; set; }
        public categorieVoiture categorie { get; set; }
        public decimal TotalPrice => (decimal)(prix * nombre);
    }
}

Controllers/PneuController.cs
using Humanizer.Localisation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SendGrid.Helpers.Mail;
using WebApplication3.Data;
using WebApplication3.Data.enums;
using WebApplication3.Models;
using WebApplication3.Models.Produits;
using WebApplication3.Models.roue;

namespace WebApplication3.Controllers
{
    public class PneuController : Controller
    {
        private readonly ApplicationDbContext _context;
        public PneuController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var viewModel = new Pneu
            {
                mainsOeuvres = await _context.mainsOeuvres.Take(4).ToListAsync(),
                roue = await _context.roue.Take(4).ToListAsync(),
                gentes = await _context.gentes.Take(4).ToListAsync(),
                Pneus = await _context.pneus.Take(4).ToListAsync(),
            };
            return View(viewModel);
        }

        #region Services

        [HttpPost]

        public IActionResult AddService(int id)
        {
            var nombre = _context.mainsOeuvres.Find(id);
            if (nombre != null)
            {
                nombre.nombre++;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult removeService(int id)
        {
            var nombre = _context.mainsOeuvres.Find(id);
            if (nombre != null)
            {
                if (nombre.nombre > 0)
                {
                    nombre.nombre--;
                }
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public IActionResult restartmainsOeuvres(int id)
        {
            var nombre = _context.mainsOeuvres.Find(id);
            if (nombre != null)
            {
                nombre.nombre = 0;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> moreServices()
        {
            var data = await _context.mainsOeuvres.ToListAsync();
            return View(data);
        }

        public IActionResult CreateServices()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateServices(MainsOeuvre mainsOeuvres)
        {
            if (!ModelState.IsValid)
            {
                if (_context.mainsOeuvres.Any(d => d.Id.Equals(mainsOeuvres.Id)))
                {
                    ViewBag.Erreur = "Cet auteur existe deja";
                    return View(mainsOeuvres);
                }
                _context.mainsOeuvres.Add(mainsOeuvres);
                _context.SaveChanges();
                return RedirectToAction("index");
            }
            return RedirectToAction(nameof(CreateServices));
        }
        public IActionResult EditServices(int id)
        {
            MainsOeuvre MainsOeuvre = _context.mainsOeuvres.FirstOrDefault(a => a.Id.Equals(id));
            if (MainsOeuvre == null)
            {
                return View("NotFound");
            }
            return View(MainsOeuvre);
        }
        [HttpPost]
        public IActionResult EditServices(MainsOeuvre mainsOeuvres)
        {
            if (_context.mainsOeuvres.Any(a => a.Id.Equals(mainsOeuvres.Id)))
            {
                _context.mainsOeuvres.Update(mainsOeuvres);
                _context.SaveChanges();
                return RedirectToAction("index");
            }
            ViewBag.Erreur = "Ce diplome n'existe pas";
            return RedirectToAction("index");

        }
        public IActionResult DetailsServices(int id)
        {
            var MainsOeuvreDetails = _context.mainsOeuvres.FirstOrDefault(a => a.Id == id);
            if (MainsOeuvreDetails == null)
            {
                return View("NotFound");
            }
            return View(MainsOeuvreDetails);
        }
        public IActionResult DeleteServices(int id)
        {
            MainsOeuvre MainsOeuvre = _context.mainsOeuvres.FirstOrDefault(d => d.Id.Equals(id));
            if (MainsOeuvre == null)
            {
                return NotFound();
            }
            return View(MainsOeuvre);
        }
        [HttpPost]
        public IActionResult DeleteServices(MainsOeuvre MainsOeuvre)
        {
            _context.mainsOeuvres.Remove(MainsOeuvre);
            _context.SaveChanges();
            return RedirectToAction("index");
        }
        #endregion

        #region Roue
        [HttpPost]
        public IActionResult AddRoue(int id)
        {
            var nombre = _context.roue.Find(id);
            if (nombre != null)
            {
                nombre.nombre++;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult removeRoue(int id)
        {
            var nombre = _context.roue.Find(id);
            if (nombre != null)
            {
                if (nombre.nombre > 0)
                {
                    nombre.nombre--;
                }
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult restartroue(int id)
        {
            var nombre = _context.roue.Find(id);
            if (nombre != null)
            {
                nombre.nombre = 0;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> moreRoue()
        {
            var data = await _context.roue.ToListAsync();
            return View(data);
        }


        public IActionResult CreateRoue()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRoue(Roue roue)
        {
            if (!ModelState.IsValid)
            {
                if (_context.roue.Any(d => d.Id.Equals(roue.Id)))
                {
                    ViewBag.Erreur = "Cet auteur existe deja";
                    return View(roue);
                }
                _context.roue.Add(roue);
                _context.SaveChanges();
                return RedirectToAction("index");
            }
            return RedirectToAction(nameof(CreateRoue));
        }
        public IActionResult EditRoue(int id)
        {
            Roue Roue = _context.roue.FirstOrDefault(a => a.Id.Equals(id));
            if (Roue == null)
            {
                return View("NotFound");
            }
            return View(Roue);
        }
        [HttpPost]
        public IActionResult EditRoue(Roue roue)
        {
            if (_context.roue.Any(a => a.Id.Equals(roue.Id)))
            {
                _context.roue.Update(roue);
                _context.SaveChanges();
                return RedirectToAction("index");
            }
            ViewBag.Erreur = "Ce diplome n'existe pas";
            return RedirectToAction("index");

        }
        public IActionResult DetailsRoue(int id)
        {
            var RoueDetails = _context.roue.FirstOrDefault(a => a.Id == id);
            if (RoueDetails == null)
            {
                return View("NotFound");
            }
            return View(RoueDetails);
        }
        public IActionResult DeleteRoue(int id)
        {
            Roue Roue = _context.roue.FirstOrDefault(d => d.Id.Equals(id));
            if (Roue == null)
            {
                return NotFound();
            }
            return View(Roue);
        }
        [HttpPost]
        public IActionResult DeleteRoue(Roue Roue)
        {
            _context.roue.Remove(Roue);
            _context.SaveChanges();
            return RedirectToAction("index");
        }
        #endregion

        #region Gentes
        [HttpPost]
        public IActionResult AddGentes(int id)
        {
            var nombre = _context.gentes.Find(id);
            if (nombre != null)
            {
                nombre.nombre++;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult removeGentes(int id)
        {
            var nombre = _context.gentes.Find(id);
            if (nombre != null)
            {
                if (nombre.nombre > 0)
                {
                    nombre.nombre--;
                }
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult restartgentes(int id)
        {
            var nombre = _context.gentes.Find(id);
            if (nombre != null)
            {
                nombre.nombre = 0;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> moreGentes()
        {
            var data = await _context.gentes.ToListAsync();
            return View(data);
        }

        public IActionResult CreateGentes()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateGentes(Gentes gentes)
        {
            if (!ModelState.IsValid)
            {
                if (_context.gentes.Any(d => d.Id.Equals(gentes.Id)))
                {
                    ViewBag.Erreur = "Cet auteur existe deja";

Controllers/VoituresController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SendGrid.Helpers.Mail;
using WebApplication3.Data;
using WebApplication3.Data.enums;
using WebApplication3.Models;
using WebApplication3.Models.roue;

namespace WebApplication3.Controllers
{
    public class VoituresController : Controller
    {
        private readonly ApplicationDbContext _context;
        public VoituresController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var couleurs = Enum.GetValues(typeof(categorieVoiture))
                               .Cast<categorieVoiture>()
                               .Select(e => new SelectListItem
                               {
                                   Value = ((int)e).ToString(),
                                   Text = e.ToString()
                               });

            ViewBag.CouleursListe = couleurs;

            var categories = Enum.GetValues(typeof(categorieVoiture)).Cast<categorieVoiture>();
            ViewBag.Categories = new SelectList(categories);

            var data = await _context.voitures.Take(6).ToListAsync();
            return View(data);
        }
        public async Task<IActionResult> more()
        {

            //var categories = Enum.GetValues(typeof(categorieVoiture))
            //                     .Cast<categorieVoiture>()
            //                     .Select(c => new SelectListItem
            //                     {
            //                         Value = ((int)c).ToString(),
            //                         Text = c.ToString()
            //                     });

            //ViewBag.Categories = categories;

            var couleurs = Enum.GetValues(typeof(categorieVoiture))
                               .Cast<categorieVoiture>()
                               .Select(e => new SelectListItem
                               {
                                   Value = ((int)e).ToString(),
                                   Text = e.ToString()
                               });

            ViewBag.CouleursListe = couleurs;

            var categories = Enum.GetValues(typeof(categorieVoiture)).Cast<categorieVoiture>();
            ViewBag.Categories = new SelectList(categories);


            var data = await _context.voitures.ToListAsync();
            return View(data);

        }

        [HttpPost]
        public IActionResult AfficherParCategorie(categorieVoiture categorie)
        {
            var categories = Enum.GetValues(typeof(categorieVoiture)).Cast<categorieVoiture>();
            ViewBag.Categories = new SelectList(categories);

            var produits = _context.voitures.Where(p => p.categorie == categorie).ToList();
            if (produits.Count == 0)
            {
                return View("NotFound");
            }
            return View(produits);
        }

        [HttpPost]
        public IActionResult restart(int id)
        {
            var nombre = _context.voitures.Find(id);
            if (nombre != null)
            {
                nombre.nombre = 0;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        #region Voiture
        [HttpPost]
        public async Task<IActionResult> AddVoiture(int id)
        {
            var nombre = await _context.voitures.FindAsync(id);
            if (nombre != null)
            {   
                nombre.nombre++;
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult removeVoiture(int id)
        {
            var nombre = _context.voitures.Find(id);
            if (nombre != null)
            {
                if (nombre.nombre > 0)
                {
                    nombre.nombre--;
                }
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        #endregion

        #region Crud 
        public IActionResult CreateVoiture()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateVoiture(Voiture voitures)
        {
            if (!ModelState.IsValid)
            {
                if (_context.voitures.Any(d => d.Id.Equals(voitures.Id)))
                {
                    ViewBag.Erreur = "Cet auteur existe deja";
                    return View(voitures);
                }
                _context.voitures.Add(voitures);
                _context.SaveChanges();
                return RedirectToAction("index");
            }
            return RedirectToAction(nameof(CreateVoiture));
        }
        public IActionResult EditVoiture(int id)
        {
            Voiture Voiture = _context.voitures.FirstOrDefault(a => a.Id.Equals(id));
            if (Voiture == null)
            {
                return View("NotFound");
            }
            return View(Voiture);
        }
        [HttpPost]
        public IActionResult EditVoiture(Voiture Voiture)
        {
            if (_context.voitures.Any(a => a.Id.Equals(Voiture.Id)))
            {
                _context.voitures.Update(Voiture);
                _context.SaveChanges();
                return RedirectToAction("index");
            }
            ViewBag.Erreur = "Ce diplome n'existe pas";
            return RedirectToAction("index");

        }
        public IActionResult DetailsVoiture(int id)
        {
            var VoitureDetails = _context.voitures.FirstOrDefault(a => a.Id == id);
            if (VoitureDetails == null)
            {
                return View("NotFound");
            }
            return View(VoitureDetails);
        }
        public IActionResult DeleteVoiture(int id)
        {
            Voiture Voiture = _context.voitures.FirstOrDefault(d => d.Id.Equals(id));
            if (Voiture == null)
            {
                return NotFound();
            }
            return View(Voiture);
        }
        [HttpPost]
        public IActionResult DeleteVoiture(Voiture Voiture)
        {
            _context.voitures.Remove(Voiture);
            _context.SaveChanges();
            return RedirectToAction("index");
        }
        #endregion
    }
}

Views/Voitures/AfficherParCategorie.cshtml
@model IEnumerable<WebApplication3.Models.Voiture>

<h2>Liste de Voitures par Catégorie</h2>


<form class="boutonB" asp-controller="Voitures" asp-action="AfficherParCategorie" method="post" style="padding: 0px">
    @Html.DropDownList("categorie", ViewBag.Categories as SelectList, "Sélectionner une catégorie")
    <input type="submit" value="Filtrer" />
</form>

<form>
        <div class="d-flex justify-content-between">
            <p class="position-fixed" style="left:10px; z-index:1">
            <a class="btn btn-secondary m-1" asp-controller="Voitures" asp-action="more"><i class="bi bi-plus"></i>Back</a>
            </p>
        </div>
</form>

@* partie services *@
<div class="noServices">
    <div class="row justify-content-around">
        <div class="col-md-4">

            <div class="desroues">

                <div class="noServices">
                    <h2 class="titreserviceVoiture">Nos Voitures</h2>
                    <div class="liga">
                        <hr class="barre" />
                        <img src="~/asp/Steering Wheel.png" class="volan" />
                        <hr class="barre" />
                    </div>
                    <div class="nosvoiture">
                        @foreach (var item in Model)
                        {
                                <div class="boxvoiture1">
                                    <div class="imgvoiture">
                                        <img src="@item.image" class="voiture" />
                                    </div>
                                    <h4 style="color:aqua">
                                        @item.nom
                                    </h4>
                                    <div class="txt1">
                                        <h7>@item.prix $</h7>
                                        <h7>vous @item.nombre</h7>
                                    </div>
                                    <div class="panierB flex-column d-flex">

                                        <form class="boutonB" asp-controller="Voitures" asp-action="AddVoiture" method="post">
                                            <input type="hidden" name="id" value="@item.Id" />
                                        <button class="buttonM">
                                                <a class="boutonA">
                                                    <img src="~/asp/buy.png" alt="buy" />
                                                    <span>Ajouter Au panier</span>
                                                </a>
                                            </button>
                                        </form>

                                        <form class="boutonB" asp-controller="Voitures" asp-action="removeVoiture" method="post">
                                            <input type="hidden" name="id" value="@item.Id" />
                                            <button class="buttonM" type="submit">
                                                <a class="boutonA">
                                                    <img src="~/asp/return purchase.png" />
                                                    <span>retirer du panier</span>
                                                </a>
                                            </button>
                                        </form>
                                    </div>

                                </div>
                        }
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

Views/Voitures/CreateVoiture.cshtml
@using WebApplication3.Data.enums
@model WebApplication3.Models.Voiture

@{
    ViewData["Title"] = "CreateVoiture";
}

<h1>CreateVoiture</h1>

<h4>Voiture</h4>
<hr />
<div class="row">
    <div class="col-md-5">
        <form asp-action="CreateVoiture">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="image" class="control-label"></label>
                <input asp-for="image" class="form-control" />
                <span asp-validation-for="image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nom" class="control-label"></label>
                <input asp-for="nom" class="form-control" />
                <span asp-validation-for="nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="prix" class="control-label"></label>
                <input asp-for="prix" class="form-control" />
                <span asp-validation-for="prix" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="categorie" class="control-label"></label>
                <select asp-for="categorie" class="form-control" asp-items="Html.GetEnumSelectList<categorieVoiture>()"></select>
                <span asp-validation-for="categorie" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-around" style="padding-top: 20px; padding-bottom : 20px">
                <input type="submit" value="Create" class="btn btn-outline-primary" />
                <a class="btn btn-outline-success align-middle" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
    <div class="col-md-5">
        <!--Ajouter la previsualisation d'une photo de profile-->
        <div class="form-group text-center">
            <img id="PhotoProfilePreview" style="max-width: 530px;max-height: 300px;" />
        </div>
        <!--Fin-->
    </div>
</div>



<!--Ajouter la previsualisation d'une photo de profile-->
@section Scripts {
    <script>
        $(document).ready(function () {
            var output = document.getElementById('PhotoProfilePreview');
            const inputImage = document.getElementById("image");
            output.src = inputImage.value;
        })
        $("#image").on("change", function () {
            var output = document.getElementById('PhotoProfilePreview');
            output.src = $(this).val();
        })

    </script>
}
<!--Fin-->

Views/Voitures/NotFound.cshtml



<form>
    <div class="d-flex justify-content-between">
        <p class="position-fixed" style="left:10px; z-index:1">
            <a class="btn btn-secondary m-1" asp-controller="Voitures" asp-action="more"><i class="bi bi-arrow-left"></i>Back</a>
        </p>
    </div>
</form>

<div class="bgNotFound">

    <div class="text-center">
        <h1 class="display-4">Desole</h1>
        <h1 class="display-3">Aucune voiture ne correspond a votre recherche</h1>
        <p>Une voiture, bien plus qu’un simple moyen de transport.</p>
    </div>
</div>

Views/Voitures/more.cshtml
@model IEnumerable<WebApplication3.Models.Voiture>

@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<h2>Liste de Voitures par Catégorie</h2>

<form class="boutonB" asp-controller="Voitures" asp-action="AfficherParCategorie" method="post" style="padding: 0px">
    @Html.DropDownList("categorie", ViewBag.Categories as SelectList, "Sélectionner une catégorie")
    <input type="submit" value="Filtrer" />
</form>

@* partie services *@
<div class="noServices">
    <div class="row justify-content-around">
        <div class="col-md-4">

            <div class="desroues">

                <div class="noServices">
                    <h2 class="titreserviceVoiture">Nos Voitures</h2>
                    <div class="liga">
                        <hr class="barre" />
                        <img src="~/asp/Steering Wheel.png" class="volan" />
                        <hr class="barre" />
                    </div>
                    @if (User.IsInRole("Admin"))
                    {
                        <div class="d-flex justify-content-between">
                            <h1>Voiture</h1>
                            <p class="position-fixed" style="right:10px; z-index:1">
                                <a class="boutonB" asp-controller="Pneu" asp-action="CreateVoiture" style="padding-top: 10px; border-radius: 10px:">
                                    <i class="bi bi-plus"></i> <span>Ajouter une voiture</span>
                                </a>
                            </p>
                        </div>
                    }
                    <div class="nosvoiture">
                        @foreach (var item in Model)
                        {
                            <div class="boxvoiture1">
                                <div class="imgvoiture">
                                    <img src="@item.image" class="voiture" />
                                </div>
                                <h4 style="color:white">
                                    @item.nom
                                </h4>
                                <div class="d-flex flex-column text-center">
                                    <h7 style="margin: 0px;">@item.prix $</h7>
                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        @if (!User.IsInRole("Admin"))
                                        {
                                            <span> quantité d’articles dans le pannier : @item.nombre</span>
                                        }
                                    }
                                </div>
                                <div class="panierB flex-column d-flex">
                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        @if (User.IsInRole("Admin"))
                                        {

                                            <a class="boutonB" asp-controller="Pneu" asp-action="EditVoiture" Asp-route-id="@item.Id" style="padding-top: 10px;">
                                                <input type="hidden" name="id" value="@item.Id" />
                                                <button class="buttonM d-flex gap-2 text-white">
                                                    <i class="bi bi-pencil-square"></i> <span>Modifier</span>
                                                </button>
                                            </a>

                                            <a class="boutonB" asp-controller="Pneu" asp-action="DeleteVoiture" Asp-route-id="@item.Id" style="padding-top: 10px;">
                                                <input type="hidden" name="id" value="@item.Id" />
                                                <button class="buttonM d-flex gap-2 text-white" type="submit">
                                                    <i class="bi bi-trash"></i>Delete
                                                </button>
                                            </a>
                                        }
                                        else
                                        {
                                            <form class="boutonB" asp-controller="Voitures" asp-action="AddVoiture" method="post">
                                                <input type="hidden" name="id" value="@item.Id" />
                                                <button class="buttonM">
                                                    <a class="boutonA">
                                                        <img src="~/asp/buy.png" alt="buy" />
                                                        <span>Ajouter Au panier</span>
                                                    </a>
                                                </button>
                                            </form>

                                            <form class="boutonB" asp-controller="Voitures" asp-action="removeVoiture" method="post">
                                                <input type="hidden" name="id" value="@item.Id" />
                                                <button class="buttonM" type="submit">
                                                    <a class="boutonA">
                                                        <img src="~/asp/return purchase.png" />
                                                        <span>retirer du panier</span>
                                                    </a>
                                                </button>
                                            </form>
                                        }
                                    }
                                    else
                                    {
                                        <form class="boutonB" asp-area="Identity" asp-page="/Account/Register">
                                            <input type="hidden" name="id" value="@item.Id" />
                                            <button class="buttonM" type="submit">
                                                <a class="boutonA">
                                                    <img src="~/asp/buy.png" alt="buy" />
                                                    <span>Ajouter Au panier</span>
                                                </a>
                                            </button>
                                        </form>

                                        <form class="boutonB" asp-area="Identity" asp-page="/Account/Login">
                                            <input type="hidden" name="id" value="@item.Id" />
                                            <button class="buttonM" type="submit">
                                                <a class="boutonA">
                                                    <img src="~/asp/return purchase.png" />
                                                    <span>retirer du panier</span>
                                                </a>
                                            </button>
                                        </form>
                                    }
                                </div>

                            </div>
                        }
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>