Models/Produit.cs
using System.ComponentModel.DataAnnotations;
using System.Composition.Convention;
using WebApplication3.Models.Produits;

namespace WebApplication3.Models
{
    public class Produit
    {
        [Key]
        public int Id { get; set; }
        public List<freins> freins { get; set; }
        public List<batterie> batteries { get; set; }
        public List<moteur> moteurs { get; set;}
        public List<Suspension> suspensions { get; set; }
        public List<TurboCompresseur> turboCompresseur { get; set; }
    }
}

Models/Produits/Suspension.cs
using System.ComponentModel.DataAnnotations;
using WebApplication3.Data.enums;

namespace WebApplication3.Models.Produits
{
    public class Suspension
    {
        [Key]
        public int Id { get; set; }
        public string image { get; set; }
        public double prix { get; set; }
        public int nombre { get; set; }
        public marque marque { get; set; }
        public decimal TotalPrice => (decimal)(prix * nombre);
    }
}

Models/Produits/TurboCompresseur.cs
using System.ComponentModel.DataAnnotations;
using WebApplication3.Data.enums;

namespace WebApplication3.Models.Produits
{
    public class TurboCompresseur
    {
        [Key]
        public int Id { get; set; }
        public string image { get; set; }
        public double prix { get; set; }
        public int nombre { get; set; }
        public marque marque { get; set; }
        public decimal TotalPrice => (decimal)(prix * nombre);
    }
}

Models/Produits/batterie.cs
using System.ComponentModel.DataAnnotations;
using WebApplication3.Data.enums;

namespace WebApplication3.Models.Produits
{
    public class batterie
    {
        [Key]
        public int Id { get; set; }
        public string image { get; set; }
        public double prix { get; set; }
        public int nombre { get; set; }
        public marque marque { get; set; }
        public decimal TotalPrice => (decimal)(prix * nombre);
    }
}

Models/Produits/freins.cs
using System.ComponentModel.DataAnnotations;
using WebApplication3.Data.enums;

namespace WebApplication3.Models.Produits
{
    public class freins
    {
        [Key]
        public int Id { get; set; }
        public string image { get; set; }
        public double prix { get; set; }
        public int nombre { get; set; }
        public marque marque { get; set; }
        public decimal TotalPrice => (decimal)(prix * nombre);
    }
}

Models/Produits/moteur.cs
using System.ComponentModel.DataAnnotations;
using WebApplication3.Data.enums;

namespace WebApplication3.Models.Produits
{
    public class moteur
    {
        [Key]
        public int Id { get; set; }
        public string image { get; set; }
        public double prix { get; set; }
        public int nombre { get; set; }
        public marque marque { get; set; }
        public decimal TotalPrice => (decimal)(prix * nombre);
    }
}

Controllers/ProduitsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication3.Data;
using WebApplication3.Data.enums;
using WebApplication3.Models;
using WebApplication3.Models.Produits;

namespace WebApplication3.Controllers
{
    public class ProduitsController : Controller
    {
        public readonly ApplicationDbContext _context;
        public ProduitsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var viewModel = new Produit
            {
                batteries = await _context.batteries.Take(3).ToListAsync(),
                moteurs = await _context.moteurs.Take(3).ToListAsync(),
                suspensions = await _context.suspensions.Take(3).ToListAsync(),
                freins = await _context.freins.Take(3).ToListAsync(),
                turboCompresseur = await _context.turboCompresseur.Take(3).ToListAsync(),
            };
            return View(viewModel);
        }

        #region batteries
        [HttpPost]
        public IActionResult Addbatteries(int id)
        {
            var nombre = _context.batteries.Find(id);
            if (nombre != null)
            {
                nombre.nombre++;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult removebatteries(int id)
        {
            var nombre = _context.batteries.Find(id);
            if (nombre != null)
            {
                if (nombre.nombre > 0)
                {
                    nombre.nombre--;
                }
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult restartbatteries(int id)
        {
            var nombre = _context.batteries.Find(id);
            if (nombre != null)
            {
                nombre.nombre = 0;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> moreBatterie()
        {

            var couleurs = Enum.GetValues(typeof(marque))
                               .Cast<marque>()
                               .Select(e => new SelectListItem
                               {
                                   Value = ((int)e).ToString(),
                                   Text = e.ToString()
                               });

            ViewBag.CouleursListe = couleurs;

            var categories = Enum.GetValues(typeof(marque)).Cast<marque>();
            ViewBag.Categories = new SelectList(categories);

            var data = await _context.batteries.ToListAsync();
            return View(data);
        }

        [HttpPost]
        public IActionResult AfficherParCategorieBatterie(marque categorie)
        {
            var categories = Enum.GetValues(typeof(marque)).Cast<marque>();
            ViewBag.Categories = new SelectList(categories);

            var produits = _context.batteries.Where(p => p.marque == categorie).ToList();
            if (produits.Count == 0)
            {
                return View("NotFound");
            }
            return View(produits);
        }

        #region Crud Batterie
        public IActionResult CreateBatterie()
            {
                return View();
            }
            [HttpPost]
            public async Task<IActionResult> CreateBatterie([Bind("image, prix, marque")] batterie batteries)
            {
                if (ModelState.IsValid)
                {
                    if (_context.batteries.Any(d => d.Id.Equals(batteries.Id)))
                    {
                        ViewBag.Erreur = "Cet auteur existe deja";
                        return View(batteries);
                    }
                    _context.batteries.Add(batteries);
                    _context.SaveChanges();
                    return RedirectToAction("index");
                }
                return RedirectToAction(nameof(CreateBatterie));
            }
            public IActionResult EditBatterie(int id)
            {
                batterie batteries = _context.batteries.FirstOrDefault(a => a.Id.Equals(id));
                if (batteries == null)
                {
                    return View("NotFound");
                }
                return View(batteries);
            }
            [HttpPost]
            public IActionResult EditBatterie(batterie batteries)
            {
                if (_context.batteries.Any(a => a.Id.Equals(batteries.Id)))
                {
                    _context.batteries.Update(batteries);
                    _context.SaveChanges();
                    return RedirectToAction("index");
                }
                ViewBag.Erreur = "Ce diplome n'existe pas";
                return RedirectToAction("index");

            }
            public IActionResult DetailsBatterie(int id)
            {
                var batterieDetails = _context.batteries.FirstOrDefault(a => a.Id == id);
                if (batterieDetails == null)
                {
                    return View("NotFound");
                }
                return View(batterieDetails);
            }
            public IActionResult DeleteBatterie(int id)
            {
                batterie batteries = _context.batteries.FirstOrDefault(d => d.Id.Equals(id));
                if (batteries == null)
                {
                    return NotFound();
                }
                return View(batteries);
            }
            [HttpPost]
            public IActionResult DeleteBatterie(batterie batteries)
            {
                _context.batteries.Remove(batteries);
                _context.SaveChanges();
                return RedirectToAction("index");
            }
        #endregion
        #endregion

        #region moteurs
        [HttpPost]
        public IActionResult Addmoteurs(int id)
        {
            var nombre = _context.moteurs.Find(id);
            if (nombre != null)
            {
                nombre.nombre++;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult removemoteurs(int id)
        {
            var nombre = _context.moteurs.Find(id);
            if (nombre != null)
            {
                if (nombre.nombre > 0)
                {
                    nombre.nombre--;
                }
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult restartmoteurs(int id)
        {
            var nombre = _context.moteurs.Find(id);
            if (nombre != null)
            {
                nombre.nombre = 0;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> moreMoteur()
        {
            var couleurs = Enum.GetValues(typeof(marque))
                               .Cast<marque>()
                               .Select(e => new SelectListItem
                               {
                                   Value = ((int)e).ToString(),
                                   Text = e.ToString()
                               });

            ViewBag.CouleursListe = couleurs;

            var categories = Enum.GetValues(typeof(marque)).Cast<marque>();
            ViewBag.Categories = new SelectList(categories);

            var data = await _context.moteurs.ToListAsync();
            return View(data);
        }

        [HttpPost]
        public IActionResult AfficherParCategorieMoteur(marque categorie)
        {
            var categories = Enum.GetValues(typeof(marque)).Cast<marque>();
            ViewBag.Categories = new SelectList(categories);

            var produits = _context.moteurs.Where(p => p.marque == categorie).ToList();
            if (produits.Count == 0)
            {
                return View("NotFound");
            }
            return View(produits);
        }

        #region Crud Moteur
        public IActionResult CreateMoteur()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateMoteur([Bind("image, prix, marque")] moteur moteurs)
        {
            if (ModelState.IsValid)
            {
                if (_context.moteurs.Any(d => d.Id.Equals(moteurs.Id)))
                {
                    ViewBag.Erreur = "Cet auteur existe deja";
                    return View(moteurs);
                }
                _context.moteurs.Add(moteurs);
                _context.SaveChanges();
                return RedirectToAction("index");
            }
            return RedirectToAction(nameof(CreateMoteur));
        }
        public IActionResult EditMoteur(int id)
        {
            moteur moteurs = _context.moteurs.FirstOrDefault(a => a.Id.Equals(id));
            if (moteurs == null)
            {
                return View("NotFound");
            }
            return View(moteurs);
        }
        [HttpPost]
        public IActionResult EditMoteur(moteur moteurs)
        {
            if (_context.moteurs.Any(a => a.Id.Equals(moteurs.Id)))
            {
                _context.moteurs.Update(moteurs);
                _context.SaveChanges();
                return RedirectToAction("index");
            }
            ViewBag.Erreur = "Ce diplome n'existe pas";
            return RedirectToAction("index");

        }

Views/Produits/AfficherParCategorieBatterie.cshtml
@model IEnumerable<WebApplication3.Models.Produits.batterie>

@{
    ViewData["Title"] = "moreBatterie";
}


<h2>Liste de Batterie par marque</h2>

<form>
    <div class="d-flex justify-content-between">
        <p class="position-fixed" style="left:10px; z-index:1">
            <a class="btn btn-secondary m-1" asp-controller="Produits"  asp-action="Index"><i class="bi bi-arrow-left"></i>Back</a>
        </p>
    </div>
</form>

<form class="boutonB" asp-controller="Produits" asp-action="AfficherParCategorieBatterie" method="post" style="padding: 0px">
    @Html.DropDownList("categorie", ViewBag.Categories as SelectList, "Sélectionner une catégorie")
    <input type="submit" value="Filtrer" />
</form>

@* //prtie batteries *@

<div class="desroues">

    <div class="noServices">
        <h2 class="titreservice">Nos batteries</h2>
        <div class="lig">
            <hr class="barre" />
            <img src="~/asp/Steering Wheel.png" class="volan" />
            <hr class="barre" />
        </div>
        <div class="ligne">
            <div class="element">
                @foreach (var item in Model)
                {
                    <div class="boxrou">
                        <div class="imgrou">
                            <img src="@item.image" class="pneu" />
                        </div>
                        <div class="txt1">
                            <h7>@item.prix $</h7>
                            @if (SignInManager.IsSignedIn(User))
                            {
                                @if (!User.IsInRole("Admin"))
                                {
                                    <span> quantité d’articles dans le pannier : @item.nombre</span>
                                }
                            }
                        </div>
                        <div class="panierB">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                @if (User.IsInRole("Admin"))
                                {
                                    <a class="boutonB" asp-controller="Produits"  asp-action="EditBatterie" Asp-route-id="@item.Id" style="padding-top: 10px;">
                                        <input type="hidden" name="id" value="@item.Id" />
                                        <button class="buttonM">
                                            <i class="bi bi-pencil-square"></i>
                                        </button>
                                    </a>

                                    <a class="boutonB" asp-controller="Produits"  asp-action="DeleteBatterie" Asp-route-id="@item.Id" style="padding-top: 10px;">
                                        <input type="hidden" name="id" value="@item.Id" />
                                        <button class="buttonM" type="submit">
                                            <i class="bi bi-trash"></i>
                                        </button>
                                    </a>
                                }
                                else
                                {
                                    <form class="boutonB" asp-controller="Produits"  asp-action="Addbatteries" method="post">
                                        <input type="hidden" name="id" value="@item.Id" />
                                        <button class="buttonM">

                                            <img src="~/asp/buy.png" alt="buy" />

                                        </button>
                                    </form>

                                    <form class="boutonB" asp-controller="Produits"  asp-action="removebatteries" method="post">
                                        <input type="hidden" name="id" value="@item.Id" />
                                        <button class="buttonM" type="submit">

                                            <img src="~/asp/return purchase.png" />

                                        </button>
                                    </form>
                                }
                            }
                            else
                            {
                                <form class="boutonB" asp-area="Identity" asp-page="/Account/Login">
                                    <input type="hidden" name="id" value="@item.Id" />
                                    <button class="buttonM">

                                        <img src="~/asp/buy.png" alt="buy" />

                                    </button>
                                </form>

                                <form class="boutonB" asp-area="Identity" asp-page="/Account/Login">
                                    <input type="hidden" name="id" value="@item.Id" />
                                    <button class="buttonM" type="submit">

                                        <img src="~/asp/return purchase.png" />

                                    </button>
                                </form>
                            }

                        </div>

                    </div>
                }
            </div>

            <div class="d-flex justify-content-evenly" style="width:100%; margin-top: 20px">
                <form class="boutonB" asp-controller="Produits"  asp-action="moreBatterie">
                    <button class="buttonM">
                        <a class="boutonA">
                            <span>Voire d'autre Bate</span>
                        </a>
                    </button>
                </form>
                @if (User.IsInRole("Admin"))
                {
                    <a class="boutonB" asp-controller="Produits"  asp-action="CreateBatterie" style="padding-top: 10px;">
                        <i class="bi bi-plus"></i> <span>Ajouter une roue</span>
                    </a>
                }
            </div>

        </div>
    </div>
</div>

Views/Produits/moreBatterie.cshtml
@model IEnumerable<WebApplication3.Models.Produits.batterie>

@{
    ViewData["Title"] = "moreBatterie";
}


<h2>Liste de Batterie par marque</h2>

<form>
    <div class="d-flex justify-content-between">
        <p class="position-fixed" style="left:10px; z-index:1">
            <a class="btn btn-secondary m-1" asp-controller="Produits"  asp-action="Index"><i class="bi bi-arrow-left"></i>Back</a>
        </p>
    </div>
</form>

<form class="boutonB" asp-controller="Produits" asp-action="AfficherParCategorieBatterie" method="post" style="padding: 0px">
    @Html.DropDownList("categorie", ViewBag.Categories as SelectList, "Sélectionner une catégorie")
    <input type="submit" value="Filtrer" />
</form>

@* //prtie batteries *@

<div class="desroues">

    <div class="noServices">
        <h2 class="titreservice">Nos batteries</h2>
        <div class="lig">
            <hr class="barre" />
            <img src="~/asp/Steering Wheel.png" class="volan" />
            <hr class="barre" />
        </div>
        <div class="ligne">
            <div class="element">
                @foreach (var item in Model)
                {
                    <div class="boxrou">
                        <div class="imgrou">
                            <img src="@item.image" class="pneu" />
                        </div>
                        <div class="txt1">
                            <h7>@item.prix $</h7>
                            @if (SignInManager.IsSignedIn(User))
                            {
                                @if (!User.IsInRole("Admin"))
                                {
                                    <span> quantité d’articles dans le pannier : @item.nombre</span>
                                }
                            }
                        </div>
                        <div class="panierB">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                @if (User.IsInRole("Admin"))
                                {
                                    <a class="boutonB" asp-controller="Produits"  asp-action="EditBatterie" Asp-route-id="@item.Id" style="padding-top: 10px;">
                                        <input type="hidden" name="id" value="@item.Id" />
                                        <button class="buttonM">
                                            <i class="bi bi-pencil-square"></i>
                                        </button>
                                    </a>

                                    <a class="boutonB" asp-controller="Produits"  asp-action="DeleteBatterie" Asp-route-id="@item.Id" style="padding-top: 10px;">
                                        <input type="hidden" name="id" value="@item.Id" />
                                        <button class="buttonM" type="submit">
                                            <i class="bi bi-trash"></i>
                                        </button>
                                    </a>
                                }
                                else
                                {
                                    <form class="boutonB" asp-controller="Produits"  asp-action="Addbatteries" method="post">
                                        <input type="hidden" name="id" value="@item.Id" />
                                        <button class="buttonM">

                                            <img src="~/asp/buy.png" alt="buy" />

                                        </button>
                                    </form>

                                    <form class="boutonB" asp-controller="Produits"  asp-action="removebatteries" method="post">
                                        <input type="hidden" name="id" value="@item.Id" />
                                        <button class="buttonM" type="submit">

                                            <img src="~/asp/return purchase.png" />

                                        </button>
                                    </form>
                                }
                            }
                            else
                            {
                                <form class="boutonB" asp-area="Identity" asp-page="/Account/Login">
                                    <input type="hidden" name="id" value="@item.Id" />
                                    <button class="buttonM">

                                        <img src="~/asp/buy.png" alt="buy" />

                                    </button>
                                </form>

                                <form class="boutonB" asp-area="Identity" asp-page="/Account/Login">
                                    <input type="hidden" name="id" value="@item.Id" />
                                    <button class="buttonM" type="submit">

                                        <img src="~/asp/return purchase.png" />

                                    </button>
                                </form>
                            }

                        </div>

                    </div>
                }
            </div>

            <div class="d-flex justify-content-evenly" style="width:100%; margin-top: 20px">
                <form class="boutonB" asp-controller="Produits"  asp-action="moreBatterie">
                    <button class="buttonM">
                        <a class="boutonA">
                            <span>Voire d'autre Bate</span>
                        </a>
                    </button>
                </form>
                @if (User.IsInRole("Admin"))
                {
                    <a class="boutonB" asp-controller="Produits"  asp-action="CreateBatterie" style="padding-top: 10px;">
                        <i class="bi bi-plus"></i> <span>Ajouter une roue</span>
                    </a>
                }
            </div>

        </div>
    </div>
</div>

Views/Produits/moreTurboCompresseur.cshtml
@model IEnumerable<WebApplication3.Models.Produits.TurboCompresseur>

@{
    ViewData["Title"] = "moreBatterie";
}


<h2>Liste de TurboCompresseur par marque</h2>

<form>
    <div class="d-flex justify-content-between">
        <p class="position-fixed" style="left:10px; z-index:1">
            <a class="btn btn-secondary m-1" asp-controller="Produits" asp-action="Index"><i class="bi bi-arrow-left"></i>Back</a>
        </p>
    </div>
</form>

<form class="boutonB" asp-controller="Produits" asp-action="AfficherParCategorieTurboCompresseur" method="post" style="padding: 0px">
    @Html.DropDownList("categorie", ViewBag.Categories as SelectList, "Sélectionner une catégorie")
    <input type="submit" value="Filtrer" />
</form>

@* //prtie moteurs *@

<div class="desroues">

    <div class="noServices">
        <h2 class="titreservice">Nos moteurs</h2>
        <div class="lig">
            <hr class="barre" />
            <img src="~/asp/Steering Wheel.png" class="volan" />
            <hr class="barre" />
        </div>
        <div class="ligne">
            <div class="element">
                @foreach (var item in Model)
                {
                    <div class="boxrou">
                        <div class="imgrou">
                            <img src="@item.image" class="pneu" />
                        </div>
                        <div class="txt1">
                            <h7>@item.prix $</h7>
                            @if (SignInManager.IsSignedIn(User))
                            {
                                @if (!User.IsInRole("Admin"))
                                {
                                    <span> quantité d’articles dans le pannier : @item.nombre</span>
                                }
                            }
                        </div>
                        <div class="panierB">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                @if (User.IsInRole("Admin"))
                                {
                                    <a class="boutonB" asp-controller="Produits"  asp-action="EditMoteur" Asp-route-id="@item.Id" style="padding-top: 10px;">
                                        <input type="hidden" name="id" value="@item.Id" />
                                        <button class="buttonM">
                                            <i class="bi bi-pencil-square"></i>
                                        </button>
                                    </a>

                                    <a class="boutonB" asp-controller="Produits"  asp-action="DeleteMoteur" Asp-route-id="@item.Id" style="padding-top: 10px;">
                                        <input type="hidden" name="id" value="@item.Id" />
                                        <button class="buttonM" type="submit">
                                            <i class="bi bi-trash"></i>
                                        </button>
                                    </a>
                                }
                                else
                                {
                                    <form class="boutonB" asp-controller="Produits"  asp-action="Addmoteurs" method="post">
                                        <input type="hidden" name="id" value="@item.Id" />
                                        <button class="buttonM">

                                            <img src="~/asp/buy.png" alt="buy" />

                                        </button>
                                    </form>

                                    <form class="boutonB" asp-controller="Produits"  asp-action="removemoteurs" method="post">
                                        <input type="hidden" name="id" value="@item.Id" />
                                        <button class="buttonM" type="submit">

                                            <img src="~/asp/return purchase.png" />

                                        </button>
                                    </form>
                                }
                            }
                            else
                            {
                                <form class="boutonB" asp-area="Identity" asp-page="/Account/Login">
                                    <input type="hidden" name="id" value="@item.Id" />
                                    <button class="buttonM">

                                        <img src="~/asp/buy.png" alt="buy" />

                                    </button>
                                </form>

                                <form class="boutonB" asp-area="Identity" asp-page="/Account/Login">
                                    <input type="hidden" name="id" value="@item.Id" />
                                    <button class="buttonM" type="submit">

                                        <img src="~/asp/return purchase.png" />

                                    </button>
                                </form>
                            }

                        </div>

                    </div>
                }
            </div>
            <div class="d-flex justify-content-evenly" style="width:100%; margin-top: 20px">
                <form class="boutonB" asp-controller="Produits"  asp-action="moreMoteur">
                    <button class="buttonM">
                        <a class="boutonA">
                            <span>Voire d'autre Bate</span>
                        </a>
                    </button>
                </form>
                @if (User.IsInRole("Admin"))
                {
                    <a class="boutonB" asp-controller="Produits"  asp-action="CreateMoteur" style="padding-top: 10px;">
                        <i class="bi bi-plus"></i> <span>Ajouter une roue</span>
                    </a>
                }
            </div>
        </div>
    </div>
</div>